package exception_handling;
public class Try_catch 
{
		  public static void main(String args[])
		  {  
		   try
		   {  
		    int a[]=new int[5];  
		    a[6]=30/10;  
		   }  
		   catch(Exception e){System.out.println("common task completed");}  
		  
		   System.out.println("rest of the code...");  
		 }  
		}  

